# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clock100.xdc

# Block Designs: bd/eth1/eth1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1 || ORIG_REF_NAME==eth1} -quiet] -quiet

# IP: bd/eth1/ip/eth1_mig_7series_0_0/eth1_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_mig_7series_0_0 || ORIG_REF_NAME==eth1_mig_7series_0_0} -quiet] -quiet

# IP: bd/eth1/ip/eth1_microblaze_0_2/eth1_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_microblaze_0_2 || ORIG_REF_NAME==eth1_microblaze_0_2} -quiet] -quiet

# IP: bd/eth1/ip/eth1_dlmb_v10_3/eth1_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_dlmb_v10_3 || ORIG_REF_NAME==eth1_dlmb_v10_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_ilmb_v10_3/eth1_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_ilmb_v10_3 || ORIG_REF_NAME==eth1_ilmb_v10_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_dlmb_bram_if_cntlr_3/eth1_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==eth1_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_ilmb_bram_if_cntlr_3/eth1_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==eth1_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_lmb_bram_3/eth1_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_lmb_bram_3 || ORIG_REF_NAME==eth1_lmb_bram_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_xbar_1/eth1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_xbar_1 || ORIG_REF_NAME==eth1_xbar_1} -quiet] -quiet

# IP: bd/eth1/ip/eth1_microblaze_0_axi_periph_3/eth1_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_microblaze_0_axi_periph_3 || ORIG_REF_NAME==eth1_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_microblaze_0_axi_intc_3 || ORIG_REF_NAME==eth1_microblaze_0_axi_intc_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_microblaze_0_xlconcat_3/eth1_microblaze_0_xlconcat_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_microblaze_0_xlconcat_3 || ORIG_REF_NAME==eth1_microblaze_0_xlconcat_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_mdm_1_3/eth1_mdm_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_mdm_1_3 || ORIG_REF_NAME==eth1_mdm_1_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_rst_mig_7series_0_100M_1/eth1_rst_mig_7series_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_rst_mig_7series_0_100M_1 || ORIG_REF_NAME==eth1_rst_mig_7series_0_100M_1} -quiet] -quiet

# IP: bd/eth1/ip/eth1_axi_smc_1/eth1_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_axi_smc_1 || ORIG_REF_NAME==eth1_axi_smc_1} -quiet] -quiet

# IP: bd/eth1/ip/eth1_rst_mig_7series_0_200M_3/eth1_rst_mig_7series_0_200M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_rst_mig_7series_0_200M_3 || ORIG_REF_NAME==eth1_rst_mig_7series_0_200M_3} -quiet] -quiet

# IP: bd/eth1/ip/eth1_axi_uartlite_0_0/eth1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_axi_uartlite_0_0 || ORIG_REF_NAME==eth1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/eth1/ip/eth1_axi_timer_0_0/eth1_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_axi_timer_0_0 || ORIG_REF_NAME==eth1_axi_timer_0_0} -quiet] -quiet

# IP: bd/eth1/ip/eth1_axi_ethernet_0_0/eth1_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_axi_ethernet_0_0 || ORIG_REF_NAME==eth1_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/eth1/ip/eth1_axi_ethernet_0_dma_0/eth1_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==eth1_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/eth1/ip/eth1_axi_ethernet_0_gtxclk_0/eth1_axi_ethernet_0_gtxclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth1_axi_ethernet_0_gtxclk_0 || ORIG_REF_NAME==eth1_axi_ethernet_0_gtxclk_0} -quiet] -quiet

# XDC: bd/eth1/eth1_ooc.xdc
