# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.cache/wt [current_project]
set_property parent.project_path D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.6 [current_project]
set_property ip_output_repo d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/hdl/eth1_wrapper.v
add_files D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/eth1.bd
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_mig_7series_0_0/eth1_mig_7series_0_0/user_design/constraints/eth1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_mig_7series_0_0/eth1_mig_7series_0_0/user_design/constraints/eth1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_mig_7series_0_0/eth1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_2/eth1_microblaze_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_2/eth1_microblaze_0_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_2/eth1_microblaze_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_dlmb_v10_3/eth1_dlmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_dlmb_v10_3/eth1_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_ilmb_v10_3/eth1_ilmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_ilmb_v10_3/eth1_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_dlmb_bram_if_cntlr_3/eth1_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_ilmb_bram_if_cntlr_3/eth1_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_lmb_bram_3/eth1_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_xbar_1/eth1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_mdm_1_3/eth1_mdm_1_3.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_mdm_1_3/eth1_mdm_1_3_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_rst_mig_7series_0_100M_1/eth1_rst_mig_7series_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_rst_mig_7series_0_100M_1/eth1_rst_mig_7series_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_rst_mig_7series_0_100M_1/eth1_rst_mig_7series_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_1/bd_e73a_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_1/bd_e73a_psr0_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_2/bd_e73a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_2/bd_e73a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_3/bd_e73a_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_3/bd_e73a_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_4/bd_e73a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_5/bd_e73a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_6/bd_e73a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_7/bd_e73a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_8/bd_e73a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_12/bd_e73a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_13/bd_e73a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_14/bd_e73a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_18/bd_e73a_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_19/bd_e73a_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_20/bd_e73a_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_21/bd_e73a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_22/bd_e73a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_23/bd_e73a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_27/bd_e73a_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_28/bd_e73a_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_29/bd_e73a_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_33/bd_e73a_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_34/bd_e73a_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_35/bd_e73a_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_36/bd_e73a_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_40/bd_e73a_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_41/bd_e73a_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_42/bd_e73a_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_43/bd_e73a_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_44/bd_e73a_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_45/bd_e73a_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_46/bd_e73a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_47/bd_e73a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_48/bd_e73a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_49/bd_e73a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_50/bd_e73a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/bd_0/ip/ip_51/bd_e73a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_rst_mig_7series_0_200M_3/eth1_rst_mig_7series_0_200M_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_rst_mig_7series_0_200M_3/eth1_rst_mig_7series_0_200M_3.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_rst_mig_7series_0_200M_3/eth1_rst_mig_7series_0_200M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_uartlite_0_0/eth1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_uartlite_0_0/eth1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_uartlite_0_0/eth1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_timer_0_0/eth1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_timer_0_0/eth1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_d93c_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_d93c_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_d93c_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_d93c_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_d93c_mac_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_d93c_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_d93c_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_2/bd_d93c_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_3/bd_d93c_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/bd_d93c_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/eth1_axi_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/synth/eth1_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_dma_0/eth1_axi_ethernet_0_dma_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_dma_0/eth1_axi_ethernet_0_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_dma_0/eth1_axi_ethernet_0_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_gtxclk_0/eth1_axi_ethernet_0_gtxclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_gtxclk_0/eth1_axi_ethernet_0_gtxclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_gtxclk_0/eth1_axi_ethernet_0_gtxclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/eth1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_2/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/constrs_1/new/clock100.xdc
set_property used_in_implementation false [get_files D:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/constrs_1/new/clock100.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top eth1_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth1_wrapper_utilization_synth.rpt -pb eth1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
