# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/test_FIFO/test_FIFO.srcs/sources_1/bd/DMA_FIFO/ip/DMA_FIFO_lmb_bram_0/DMA_FIFO_lmb_bram_0.xci
# IP: The module: 'DMA_FIFO_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/test_FIFO/test_FIFO.srcs/sources_1/bd/DMA_FIFO/ip/DMA_FIFO_lmb_bram_0/DMA_FIFO_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_FIFO_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/test_FIFO/test_FIFO.srcs/sources_1/bd/DMA_FIFO/ip/DMA_FIFO_lmb_bram_0/DMA_FIFO_lmb_bram_0.xci
# IP: The module: 'DMA_FIFO_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/test_FIFO/test_FIFO.srcs/sources_1/bd/DMA_FIFO/ip/DMA_FIFO_lmb_bram_0/DMA_FIFO_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_FIFO_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
