# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/eth1_axi_ethernet_0_0.xci
# IP: The module: 'eth1_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/bd_d93c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c || ORIG_REF_NAME==bd_d93c} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_d93c_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_eth_buf_0 || ORIG_REF_NAME==bd_d93c_eth_buf_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_1/bd_d93c_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_mac_0 || ORIG_REF_NAME==bd_d93c_mac_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_2/bd_d93c_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_c_shift_ram_0_0 || ORIG_REF_NAME==bd_d93c_c_shift_ram_0_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_3/bd_d93c_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_c_counter_binary_0_0 || ORIG_REF_NAME==bd_d93c_c_counter_binary_0_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_4/bd_d93c_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_xlconstant_0_0 || ORIG_REF_NAME==bd_d93c_xlconstant_0_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_5/bd_d93c_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_util_vector_logic_0_0 || ORIG_REF_NAME==bd_d93c_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/bd_d93c_ooc.xdc

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/eth1_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/synth/eth1_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/eth1_axi_ethernet_0_0.xci
# IP: The module: 'eth1_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/bd_d93c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c || ORIG_REF_NAME==bd_d93c} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_d93c_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_eth_buf_0 || ORIG_REF_NAME==bd_d93c_eth_buf_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_1/bd_d93c_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_mac_0 || ORIG_REF_NAME==bd_d93c_mac_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_2/bd_d93c_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_c_shift_ram_0_0 || ORIG_REF_NAME==bd_d93c_c_shift_ram_0_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_3/bd_d93c_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_c_counter_binary_0_0 || ORIG_REF_NAME==bd_d93c_c_counter_binary_0_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_4/bd_d93c_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_xlconstant_0_0 || ORIG_REF_NAME==bd_d93c_xlconstant_0_0} -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/ip/ip_5/bd_d93c_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d93c_util_vector_logic_0_0 || ORIG_REF_NAME==bd_d93c_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/bd_0/bd_d93c_ooc.xdc

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/eth1_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_ethernet_0_0/synth/eth1_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
