# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_xbar_1/eth1_xbar_1.xci
# IP: The module: 'eth1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_xbar_1/eth1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_xbar_1/eth1_xbar_1.xci
# IP: The module: 'eth1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dario/fulgor/trabajo_final/vivado_projects/ethernet_GMII_v1/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_xbar_1/eth1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
