#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : Micro.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Dec 29 11:04:17 -0300 2020
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Micro.sh [-help]
# usage: Micro.sh [-lib_map_path]
# usage: Micro.sh [-noclean_files]
# usage: Micro.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Micro.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_lite_ipif_v3_0_4 axi_ethernet_buffer_v2_0_22 xbip_utils_v3_0_10 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 tri_mode_ethernet_mac_v9_0_16 c_reg_fd_v12_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 xlconstant_v1_1_7 util_vector_logic_v2_0_1 microblaze_v11_0_3 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_23 axi_sg_v4_1_13 axi_dma_v7_1_22 lmb_v10_v3_0_11 lmb_bram_if_cntlr_v4_0_18 blk_mem_gen_v8_4_4 mdm_v3_2_18 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_21 axi_vip_v1_1_7 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 axi_uartlite_v2_0_25 interrupt_control_v3_1_4 axi_gpio_v2_0_23)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Micro.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/sim/Micro.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/Micro_mig_7series_0_3_mig_sim.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_mig_7series_0_3/Micro_mig_7series_0_3/user_design/rtl/Micro_mig_7series_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernet_buffer_v2_0_22 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/6cd5/hdl/axi_ethernet_buffer_v2_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_0/sim/bd_bd72_eth_buf_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work tri_mode_ethernet_mac_v9_0_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/f7d0/hdl/tri_mode_ethernet_mac_v9_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work tri_mode_ethernet_mac_v9_0_16 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/f7d0/hdl/tri_mode_ethernet_mac_v9_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/common/bd_bd72_mac_0_block_reset_sync.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/common/bd_bd72_mac_0_block_sync_block.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0_axi4_lite_ipif_top.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0_axi4_lite_ipif_wrapper.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/physical/bd_bd72_mac_0_gmii_if.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0_tx_clk_gen.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/statistics/bd_bd72_mac_0_vector_decode.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0_block.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0_support.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0_support_resets.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_bd72_mac_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_2/sim/bd_bd72_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/1f12/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_3/sim/bd_bd72_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_4/sim/bd_bd72_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/ip/ip_5/sim/bd_bd72_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/bd_0/sim/bd_bd72.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_2/sim/Micro_axi_ethernet_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work microblaze_v11_0_3 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/1efc/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_microblaze_0_1/sim/Micro_microblaze_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_23 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/af86/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_22 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/0fb1/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_dma_2/sim/Micro_axi_ethernet_0_dma_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_gtxclk_1/Micro_axi_ethernet_0_gtxclk_1_clk_wiz.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_ethernet_0_gtxclk_1/Micro_axi_ethernet_0_gtxclk_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lmb_v10_v3_0_11 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/c2ed/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_dlmb_v10_1/sim/Micro_dlmb_v10_1.vhd" \
    "$ref_dir/../../../bd/Micro/ip/Micro_ilmb_v10_1/sim/Micro_ilmb_v10_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_18 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/246e/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_dlmb_bram_if_cntlr_1/sim/Micro_dlmb_bram_if_cntlr_1.vhd" \
    "$ref_dir/../../../bd/Micro/ip/Micro_ilmb_bram_if_cntlr_1/sim/Micro_ilmb_bram_if_cntlr_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_lmb_bram_1/sim/Micro_lmb_bram_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work mdm_v3_2_18 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/e9fa/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_mdm_1_1/sim/Micro_mdm_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_rst_mig_7series_0_100M_0/sim/Micro_rst_mig_7series_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/sim/bd_c7a3.v" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_0/sim/bd_c7a3_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_1/sim/bd_c7a3_psr0_0.vhd" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_2/sim/bd_c7a3_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_3/sim/bd_c7a3_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_4/sim/bd_c7a3_arsw_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_5/sim/bd_c7a3_rsw_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_6/sim/bd_c7a3_awsw_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_7/sim/bd_c7a3_wsw_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_8/sim/bd_c7a3_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/053f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_9/sim/bd_c7a3_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_10/sim/bd_c7a3_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/9d43/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_11/sim/bd_c7a3_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_12/sim/bd_c7a3_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_13/sim/bd_c7a3_sarn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_14/sim/bd_c7a3_srn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_15/sim/bd_c7a3_sawn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_16/sim/bd_c7a3_swn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_17/sim/bd_c7a3_sbn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_18/sim/bd_c7a3_s01mmu_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_19/sim/bd_c7a3_s01tr_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_20/sim/bd_c7a3_s01sic_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_21/sim/bd_c7a3_s01a2s_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_22/sim/bd_c7a3_sarn_1.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_23/sim/bd_c7a3_srn_1.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_24/sim/bd_c7a3_s02mmu_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_25/sim/bd_c7a3_s02tr_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_26/sim/bd_c7a3_s02sic_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_27/sim/bd_c7a3_s02a2s_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_28/sim/bd_c7a3_sarn_2.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_29/sim/bd_c7a3_srn_2.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_30/sim/bd_c7a3_s03mmu_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_31/sim/bd_c7a3_s03tr_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_32/sim/bd_c7a3_s03sic_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_33/sim/bd_c7a3_s03a2s_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_34/sim/bd_c7a3_sawn_1.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_35/sim/bd_c7a3_swn_1.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_36/sim/bd_c7a3_sbn_1.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_37/sim/bd_c7a3_s04mmu_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_38/sim/bd_c7a3_s04tr_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_39/sim/bd_c7a3_s04sic_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_40/sim/bd_c7a3_s04a2s_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_41/sim/bd_c7a3_sarn_3.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_42/sim/bd_c7a3_srn_3.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_43/sim/bd_c7a3_sawn_2.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_44/sim/bd_c7a3_swn_2.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_45/sim/bd_c7a3_sbn_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_46/sim/bd_c7a3_m00s2a_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_47/sim/bd_c7a3_m00arn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_48/sim/bd_c7a3_m00rn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_49/sim/bd_c7a3_m00awn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_50/sim/bd_c7a3_m00wn_0.sv" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_51/sim/bd_c7a3_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/7af8/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/bd_0/ip/ip_52/sim/bd_c7a3_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_smc_0/sim/Micro_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_rst_mig_7series_0_200M_1/sim/Micro_rst_mig_7series_0_200M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/8b3d" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/ec67/hdl" +incdir+"D:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Micro/ip/Micro_xbar_1/sim/Micro_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_uartlite_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/43b7/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_uartlite_0_1/sim/Micro_axi_uartlite_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../project_kintex7.srcs/sources_1/bd/Micro/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Micro/ip/Micro_axi_gpio_0_1/sim/Micro_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Micro xil_defaultlib.glbl -o Micro_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Micro_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Micro.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Micro_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Micro_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Micro.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Micro.sh [-help]\n\
Usage: Micro.sh [-lib_map_path]\n\
Usage: Micro.sh [-reset_run]\n\
Usage: Micro.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
