# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DMA_FIFO/DMA_FIFO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO || ORIG_REF_NAME==DMA_FIFO} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_mig_7series_0_0/DMA_FIFO_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_mig_7series_0_0 || ORIG_REF_NAME==DMA_FIFO_mig_7series_0_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_microblaze_0_0/DMA_FIFO_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_microblaze_0_0 || ORIG_REF_NAME==DMA_FIFO_microblaze_0_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_dlmb_v10_0/DMA_FIFO_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_dlmb_v10_0 || ORIG_REF_NAME==DMA_FIFO_dlmb_v10_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_ilmb_v10_0/DMA_FIFO_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_ilmb_v10_0 || ORIG_REF_NAME==DMA_FIFO_ilmb_v10_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_dlmb_bram_if_cntlr_0/DMA_FIFO_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DMA_FIFO_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_ilmb_bram_if_cntlr_0/DMA_FIFO_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DMA_FIFO_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_lmb_bram_0/DMA_FIFO_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_lmb_bram_0 || ORIG_REF_NAME==DMA_FIFO_lmb_bram_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_xbar_0/DMA_FIFO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_xbar_0 || ORIG_REF_NAME==DMA_FIFO_xbar_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_microblaze_0_axi_periph_0/DMA_FIFO_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DMA_FIFO_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_microblaze_0_axi_intc_0/DMA_FIFO_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_microblaze_0_axi_intc_0 || ORIG_REF_NAME==DMA_FIFO_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_microblaze_0_xlconcat_0/DMA_FIFO_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_microblaze_0_xlconcat_0 || ORIG_REF_NAME==DMA_FIFO_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_mdm_1_0/DMA_FIFO_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_mdm_1_0 || ORIG_REF_NAME==DMA_FIFO_mdm_1_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axi_smc_0/DMA_FIFO_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axi_smc_0 || ORIG_REF_NAME==DMA_FIFO_axi_smc_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_rst_mig_7series_0_200M_0/DMA_FIFO_rst_mig_7series_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==DMA_FIFO_rst_mig_7series_0_200M_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axi_uartlite_0_0/DMA_FIFO_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axi_uartlite_0_0 || ORIG_REF_NAME==DMA_FIFO_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axi_dma_0_0/DMA_FIFO_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axi_dma_0_0 || ORIG_REF_NAME==DMA_FIFO_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axis_data_fifo_1_0/DMA_FIFO_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axis_data_fifo_1_0 || ORIG_REF_NAME==DMA_FIFO_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axis_data_fifo_0_0/DMA_FIFO_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axis_data_fifo_0_0 || ORIG_REF_NAME==DMA_FIFO_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axis_broadcaster_0_0/DMA_FIFO_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axis_broadcaster_0_0 || ORIG_REF_NAME==DMA_FIFO_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/DMA_FIFO/ip/DMA_FIFO_axis_combiner_0_0/DMA_FIFO_axis_combiner_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_FIFO_axis_combiner_0_0 || ORIG_REF_NAME==DMA_FIFO_axis_combiner_0_0} -quiet] -quiet

# XDC: bd/DMA_FIFO/DMA_FIFO_ooc.xdc
